# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scallop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='bank_id',
            new_name='card_num',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='email',
        ),
        migrations.AddField(
            model_name='activityapply',
            name='apply_type',
            field=models.CharField(default='推广活动申请表', editable=False, max_length=32, verbose_name='申请表类型'),
        ),
        migrations.AddField(
            model_name='baseapply',
            name='apply_id',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=32, verbose_name='部门名称'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='enrolldate',
            field=models.DateField(null=True, verbose_name='入职日期'),
        ),
    ]
