# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scallop', '0002_auto_20171102_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='enrolldate',
            new_name='enroll_date',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='englishname',
        ),
        migrations.AddField(
            model_name='activityapply',
            name='apply_name',
            field=models.CharField(default='推广活动申请表', editable=False, max_length=32, verbose_name='申请表名称'),
        ),
        migrations.AddField(
            model_name='record',
            name='note',
            field=models.CharField(max_length=64, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='english_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='英文名'),
        ),
        migrations.AlterField(
            model_name='activityapply',
            name='apply_type',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='scallop.ApplyType', verbose_name='申请表类型'),
        ),
        migrations.AlterField(
            model_name='activityapply',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='.upload/attachment/', verbose_name='上传附件'),
        ),
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '以提交'), (2, '审核中'), (3, '未通过'), (4, '通过'), (5, '通过/已付款'), (6, '以归档')], verbose_name='状态'),
        ),
    ]
