# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scallop', '0003_auto_20171102_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityapply',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='./upload/attachment/', verbose_name='上传附件'),
        ),
    ]
