# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-05 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scallop', '0005_auto_20171105_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, null=True, verbose_name='申请表具体类型')),
                ('base_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scallop.ApplyType', verbose_name='所属大类')),
            ],
        ),
    ]
