# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-05 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scallop', '0006_secondtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityapply',
            name='apply_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scallop.SecondType', verbose_name='申请表类型'),
        ),
    ]
