# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scallop', '0008_auto_20171105_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseapply',
            name='coin_capital',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='金额大写'),
        ),
    ]
