# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 03:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scallop', '0009_auto_20171107_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityapply',
            name='note',
            field=models.CharField(max_length=64, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='baseapply',
            name='apply_id',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='流水号'),
        ),
        migrations.AlterField(
            model_name='record',
            name='apply_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scallop.BaseApply', verbose_name='流水号'),
        ),
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '已提交'), (2, '审核中'), (3, '未通过'), (4, '通过'), (5, '通过/已付款'), (6, '以归档')], verbose_name='状态'),
        ),
    ]
