# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 04:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scallop', '0010_auto_20171112_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='apply_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scallop.ApplyType', verbose_name='表单类型'),
        ),
        migrations.AlterField(
            model_name='baseapply',
            name='apply_id',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='流水单号'),
        ),
        migrations.AlterField(
            model_name='baseapply',
            name='budget',
            field=models.IntegerField(verbose_name='金额'),
        ),
    ]
